// app/home/layout.tsx
import DashboardSidebar from "@/components/dashboard/dashboard-sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-white`}>
        <div className="flex min-h-screen p-2">
          <DashboardSidebar />
          <main className="flex-1 overflow-x-hidden">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}