import DashboardSidebar from "@/components/dashboard/dashboard-sidebar";
import { Sidebar } from "@/types/type";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

const siderBarList: Sidebar[] = [
  {
    name: "Home",
    link: "/home",
  },
  {
    name: "Chat",
    link: "/chat",
  },
  {
    name: "Feed",
    link: "/feed",
  },
  {
    name: "Notifications",
    link: "/notifications",
  },
];

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased text-white`}>
        <div className="flex">
          <div>
            <DashboardSidebar />
          </div>
          <div>{children}</div>
        </div>
      </body>
    </html>
  );
}
