"use client";

// import type { Metadata } from "next";
import { Nunito, Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar";
import SessionWrapper from "./sessionWrapper";
import useSocket from "@/hooks/socket";
import { useEffect } from "react";
import { sdk } from "@/utils/graphqlClient";
import { useUser } from "@/store/user";
import { User } from "@/generated/graphql";

const Montserrat = Oswald({
  variable: "--font-primary",
  subsets: ["latin"],
  weight: ["200", "400", "500", "600", "700"],
});
const Lat = Nunito({
  variable: "--font-secondary",
  subsets: ["latin"],
  weight: ["200", "500", "600", "300", "400", "700"],
});

// export const metadata: Metadata = {
//   title: "Muzup App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { connect, disconnect } = useSocket();
  const { meUser, setMeUser } = useUser();

  useEffect(() => {
    const fetch = async () => {
      try {
        const data = await sdk.meUser();
        console.log("gffff");
        if (data.meUser?._id) {
          console.log(data.meUser, "ss");
          setMeUser(data.meUser as User);
          connect(data.meUser._id);
        }
      } catch (error) {
        console.log(error);
      }
    };
    fetch();
  }, []);

  return (
    <html lang="en" className={`${Montserrat.variable} ${Lat.variable}`}>
      <SessionWrapper>
        <body className={`antialiased`}>{children}</body>
      </SessionWrapper>
    </html>
  );
}
