// app/home/layout.tsx
import DashboardSidebar from "@/components/dashboard/dashboard-sidebar";
import { sdk } from "@/utils/graphqlClient";
import type { Metadata } from "next";
import { cookies } from "next/headers";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by create next app",
};

export default async function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let count: number | undefined = undefined;
  try {
    const cookieStore = await cookies();
    const data = await sdk.getUnreadNotifications(
      {},
      { cookie: cookieStore.toString() }
    );
    count = data.getUnreadNotifications;
  } catch (error) {
    console.log(error);
  }
  return (
    <div className="flex min-h-screen p-2 max-w-7xl mx-auto">
      <DashboardSidebar unreadCount={count} />
      <main className="flex-1 overflow-x-hidden">{children}</main>
    </div>
  );
}
